theme: jekyll-theme-cayman
title: Love at First Swipe
description: A Machine Learning project which predicts whether or not two people would "match" on a date based on their preferences and values. Contributors - Roberto Esquivel, Amanda Moulaison, Amanda Pennie, Harsh Rana
