theme: jekyll-theme-cayman
title: Love at First Swipe
description: &description "A machine learning project which seeks to explain why two people "match" on a date based on initial perceptions after a 4-minute round of speed dating. \n Contributors - Roberto Esquivel, Amanda Moulaison, Amanda Pennie, Harsh Rana"
